name: $(BuildID)

trigger:
  branches:
    include:
      - devops
      - feat/*
  paths:
    exclude:
      - 'apps/boilerplate/*'
      - 'apps/digiroom/*'
      - 'apps/digiroom-cms/*'
      - 'apps/digiroom-new-car-purchase/*'
      - 'apps/digiroom-news/*'
      - 'apps/digiroom-promo/*'

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndInstall
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
      cd ../../
      npm install
    displayName: 'Change Directory and npm install'
    
- job: BuildBoilerplate
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
      cd apps/boilerplate
      npm install
      # Add your build steps for boilerplate here
    displayName: 'Build Boilerplate'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/devops') # Build only on 'devops' branch
    
- job: BuildDigiroom
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
      cd apps/digiroom
      npm install
      # Add your build steps for digiroom here
    displayName: 'Build Digiroom'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feat/') # Build only on 'feat/*' branches
