const currentDate = new Date();
currentDate.setDate(currentDate.getDate() + 1);
export const itemProduct = [
  {
    title: 'Promo Yaris',
    slug: 'wow',
    startDate: new Date().toDateString(),
    endDate: new Date().toDateString(),
    category: 'Body & Paint',
    status: 'Published',
    boolean: 'active',
  },
  {
    title: 'Promo HRV',
    slug: 'OKE',
    startDate: new Date().toDateString(),
    endDate: new Date().toDateString(),
    category: 'Body & Paint',
    status: 'Published',
    boolean: 'inactive',
  },
  {
    title: 'Promo HR',
    slug: 'wow',
    startDate: new Date().toDateString(),
    endDate: new Date().toDateString(),
    category: 'Body & Paint',
    status: 'Published',
    boolean: 'active',
  },
  {
    title: 'Promo Yaris',
    slug: 'wow',
    startDate: new Date().toDateString(),
    endDate: new Date().toDateString(),
    category: 'Body & Paint',
    status: 'Published',
    boolean: 'waitings',
  },
  {
    title: 'Promo Yaris',
    slug: 'wow',
    startDate: new Date().toDateString(),
    endDate: new Date().toDateString(),
    category: 'Body & Paint',
    status: 'Published',
    boolean: 'inactive',
  },
  {
    title: 'Promo Yaris',
    slug: 'wow',
    startDate: new Date().toDateString(),
    endDate: new Date().toDateString(),
    category: 'Body & Paint',
    status: 'Published',
    boolean: 'inactive',
  },
];
