name: $(Build.BuildId) # Corrected the variable syntax

trigger:
  branches:
    include:
      - devops
      - feat/*
  paths:
    include:
      - 'apps/digiroom-news/*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPush
  displayName: 'Build and Push'
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        cd ../../
        npm install
        cd apps/digiroom-news
    displayName: 'npm install from parent dir'

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x' # Changed to a supported Node.js version
    displayName: 'Install Node.js'

  - script: |
      cd apps/digiroom-news
      npm install
      npm run build
    displayName: 'npm install and build'
    workingDirectory: $(Build.SourcesDirectory) # Changed to use predefined variable

  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      containerRegistry: 'docker hub connection'
      repository: 'rainover922/digiroom-news'
      tags: '$(Build.BuildId)'
      buildContext: 'apps/digiroom-news' # Changed to the correct build context
    displayName: 'Build and push Docker image to ACR'
