# azure-pipeline-a.yml
name: $(BuildID)

trigger:
  branches:
    include:
      - devops
      - feat/*
  paths:
    include:
      - 'apps/boilerplate/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'build'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'docker hub connection'
    repository: 'rainover922/boilerplate'
    tags: '$(BuildID)'
    buildContext: 'apps/boilerplate'
  displayName: 'Build and push Docker image to ACR'